# ================== connection with server ====================
     spring.datasource.url=jdbc:postgresql://202.8.75.115:5432/WB_POS
     spring.datasource.username=wb_pos_01
     spring.datasource.password=wb_pos_01_2023
# ================== connection with server ====================
 

spring.jpa.hibernate.ddl-auto=update
# ============== allow image or file has size 2MB ==============
spring.servlet.multipart.max-file-size=2MB 
#spring.servlet.multipart.max-request-size=10MB
#spring.servlet.multipart.enabled=true


 
 

