# spring.profiles.active=production
 spring.profiles.active=dev

server.port=8080
# ------------------ for security authentication ------------------
     #security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
     #secret key : H@ll0_S$cr$tW0rd_JWT
     security.jwt.secret-key=d47c7bce693b2d3a551a5a7e57a811c2472e387ad77d36baa858518a00cd899e
     # 1h in millisecond
     #security.jwt.expiration-time=3600000
     #1d in millisecond
     security.jwt.expiration-time=86400000
     spring.jpa.open-in-view=false
# ------------------ for security authentication ------------------


spring.jpa.hibernate.ddl-auto=update
# ============== allow image or file has size 2MB ==============
spring.servlet.multipart.max-file-size=20MB 
spring.servlet.multipart.max-request-size=20MB
#spring.servlet.multipart.enabled=true

