
spring.datasource.url=jdbc:postgresql://localhost:5432/wb_pos_01_local
spring.datasource.username=postgres
spring.datasource.password=postgres


spring.jpa.hibernate.ddl-auto=update
# ============== allow image or file has size 2MB ==============
spring.servlet.multipart.max-file-size=2MB 
#spring.servlet.multipart.max-request-size=10MB
#spring.servlet.multipart.enabled=true

