/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Components.Event.ButtonEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.Icon;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author MOBILE-APP.02
 */
 
public class ProfileIcon extends javax.swing.JPanel {
     
     
     private Icon icon;
     
     public ProfileIcon() {
          initComponents();
     }

     public void initEvent(ButtonEvent event) {
          btnIcon.addMouseListener(new MouseListener(){
               @Override
               public void mouseClicked(MouseEvent e) {
                    event.onMouseClick();
               }

               @Override
               public void mousePressed(MouseEvent e) {
               }

               @Override
               public void mouseReleased(MouseEvent e) {
               }

               @Override
               public void mouseEntered(MouseEvent e) {
               }

               @Override
               public void mouseExited(MouseEvent e) {
               }
          
          });
          
     }

     public Icon getIcon() {
          return icon;
     }

     public void setIcon(Icon icon) {
          this.icon = icon;
          btnIcon.setIcon(icon);
     }
     
     
     
     
     /**
      * This method is called from
      * within the constructor to
      * initialize the form. WARNING: Do
      * NOT modify this code. The
      * content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          btnIcon = new javax.swing.JLabel();
          lbName = new javax.swing.JLabel();

          btnIcon.setText("profileIcone");
          btnIcon.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btnIconMouseClicked(evt);
               }
          });

          lbName.setText("jLabel1");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
          this.setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(btnIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
               .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
     }// </editor-fold>//GEN-END:initComponents

     private void btnIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIconMouseClicked
         
     }//GEN-LAST:event_btnIconMouseClicked


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel btnIcon;
     private javax.swing.JLabel lbName;
     // End of variables declaration//GEN-END:variables
}
