/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelToImageConverter;

import Components.ReceiptBox;
import Model.Reprint.ReprintModel;
import Model.Reprint.SaleDetailModel;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DecimalFormat;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author MOBILE-APP.02
 */
public class PanelData extends javax.swing.JPanel {

     /**
      * Creates new form PanelData
      */
     public PanelData() {
          initComponents();
     }
     DecimalFormat dm = new DecimalFormat("$ #,##0.00");
     DecimalFormat kh = new DecimalFormat("#,##0");
     private Icon logoIcon;
     private ReprintModel listReprint;
     private String titleCompany;
     private String titleAddress;

     public String getTitleAddress() {
          return titleAddress;
     }

     public void setTitleAddress(String titleAddress) {
          this.titleAddress = titleAddress;
          address.setText(titleAddress);
     }

     public Icon getLogoIcon() {
          return logoIcon;
     }

     public void setLogoIcon(Icon logoIcon) {
          this.logoIcon = logoIcon;
          logo.setIcon(logoIcon);
     }

     public ReprintModel getListReprint() {
          return listReprint;
     }

     public void setListReprint(ReprintModel listReprint) {
          this.listReprint = listReprint;

          SaleDetailModel[] listSale = listReprint.getSaleDetails();

          for (int i = 0; i < listSale.length; i++) {
               var list = listSale[i];
               ReceiptBox re = new ReceiptBox();
               re.setProductName(list.getProNameEn());
               re.setBarcodeStr(list.getBarcode());
               re.setQtyStr("" + list.getQty());
               re.setUnitPriceStr(dm.format(list.getPrice()));
               double amount = list.getQty() * list.getPrice();
               re.setAmountStr(dm.format(amount));
               countProduct.add(re);
               countProduct.add(Box.createRigidArea(new Dimension(2, 2)));
               countProduct.setLayout(new BoxLayout(countProduct, BoxLayout.Y_AXIS));
               countProduct.setBorder(new EmptyBorder(2, 2, 2, 2));
          }
     }

     public String getTitleCompany() {
          return titleCompany;
     }

     public void setTitleCompany(String titleCompany) {
          this.titleCompany = titleCompany;
          companyname.setText(titleCompany);
     }

     public void setFontSizeForLabels(Container container, int size) {
          Component[] components = container.getComponents();
          for (Component component : components) {
               if (component instanceof JLabel) {
                    JLabel label = (JLabel) component;
                    Font currentFont = label.getFont();
                    Font boldFont = new Font(label.getFont().getFontName(), Font.BOLD, size);
                    label.setFont(boldFont);
               } else if (component instanceof Container) {
                    setFontSizeForLabels((Container) component, size);
               }
          }

     }

     public void printComponenet(Component component) {
          PrinterJob pj = PrinterJob.getPrinterJob();
          pj.setJobName(" Print Component ");

          pj.setPrintable(new Printable() {
               public int print(Graphics pg, PageFormat pf, int pageNum) {
                    if (pageNum > 0) {
                         return Printable.NO_SUCH_PAGE;
                    }

                    Graphics2D g2 = (Graphics2D) pg;
                    g2.translate(pf.getImageableX(), pf.getImageableY());
                    component.paint(g2);
                    return Printable.PAGE_EXISTS;
               }
          });
          if (pj.printDialog() == false) {
               return;
          }

          try {
               pj.print();
          } catch (PrinterException ex) {
               // handle exception
          }
     }

     /**
      * This method is called from
      * within the constructor to
      * initialize the form. WARNING: Do
      * NOT modify this code. The
      * content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          logo = new javax.swing.JLabel();
          companyname = new javax.swing.JLabel();
          vattingValue = new javax.swing.JLabel();
          lbVattin = new javax.swing.JLabel();
          address = new javax.swing.JLabel();
          countProduct = new javax.swing.JPanel();

          setBackground(new java.awt.Color(255, 255, 255));

          logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

          companyname.setFont(new java.awt.Font("Khmer OS Muol", 1, 10)); // NOI18N
          companyname.setForeground(new java.awt.Color(56, 56, 56));
          companyname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          companyname.setText("រេដ​ អាន អិចប្រេស ឯ.ក");

          vattingValue.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
          vattingValue.setForeground(new java.awt.Color(56, 56, 56));
          vattingValue.setText("038545848965886");

          lbVattin.setFont(new java.awt.Font("Khmer OS Content", 1, 11)); // NOI18N
          lbVattin.setForeground(new java.awt.Color(56, 56, 56));
          lbVattin.setText("លេខអត្តសញ្ញាណសារពើពន្ធ​(VATTIN)៖");

          address.setFont(new java.awt.Font("Khmer OS Content", 1, 11)); // NOI18N
          address.setForeground(new java.awt.Color(56, 56, 56));
          address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          address.setText("ផ្ទះលេខ១៣៩១២ ផ្លូវ ៥៩៨ ភូមិខ១ សង្កាត់ច្រាំងចំរេះទី២  ខណ្ឌឬស្សីកែវ រាជធានីភ្នំពេញ");

          countProduct.setBackground(new java.awt.Color(102, 0, 102));

          javax.swing.GroupLayout countProductLayout = new javax.swing.GroupLayout(countProduct);
          countProduct.setLayout(countProductLayout);
          countProductLayout.setHorizontalGroup(
               countProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 331, Short.MAX_VALUE)
          );
          countProductLayout.setVerticalGroup(
               countProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 119, Short.MAX_VALUE)
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
          this.setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(companyname, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(87, 87, 87))
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(106, 106, 106)
                              .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(34, 34, 34)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbVattin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vattingValue, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(14, 14, 14)
                              .addComponent(countProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(16, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(companyname)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(lbVattin)
                         .addComponent(vattingValue, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(address)
                    .addGap(27, 27, 27)
                    .addComponent(countProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(332, Short.MAX_VALUE))
          );
     }// </editor-fold>//GEN-END:initComponents


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel address;
     private javax.swing.JLabel companyname;
     private javax.swing.JPanel countProduct;
     private javax.swing.JLabel lbVattin;
     private javax.swing.JLabel logo;
     private javax.swing.JLabel vattingValue;
     // End of variables declaration//GEN-END:variables
}
