package NewCashierReport;

import Color.WindowColor;
import Fonts.WindowFonts;

public class BoxReport extends javax.swing.JPanel {

    public BoxReport() {
        initComponents();
        name.setForeground(WindowColor.black);
        name.setFont(WindowFonts.timeNewRoman10);
        number.setForeground(WindowColor.black);
        number.setFont(WindowFonts.timeNewRoman10);
        total.setForeground(WindowColor.black);
        total.setFont(WindowFonts.timeNewRoman10);
    }
    
    private String title;
    private String num;
    private String amount;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
        name.setText("<html>"+title+"</html>");
    }

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
        number.setText(num);
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
        total.setText(amount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          number = new javax.swing.JLabel();
          total = new javax.swing.JLabel();
          name = new javax.swing.JLabel();

          setBackground(new java.awt.Color(255, 255, 255));

          number.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
          number.setForeground(new java.awt.Color(0, 0, 0));
          number.setText("75");

          total.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
          total.setForeground(new java.awt.Color(0, 0, 0));
          total.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
          total.setText("$ 680.74");

          name.setBackground(new java.awt.Color(255, 0, 0));
          name.setText("Name");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
          this.setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
          );
     }// </editor-fold>//GEN-END:initComponents


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel name;
     private javax.swing.JLabel number;
     private javax.swing.JLabel total;
     // End of variables declaration//GEN-END:variables
}
